name: Swaglabs E2E test case
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  # schedule:
  #   # - cron: '30 1 * * *'
  #   - cron: "0 6 * * 1"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Run Playwright tests
        run: npx playwright test

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: allure generate my-allure-results -o allure-report --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
         name: allure-report
         path: allure-report
    
      - name: Upload Allure Result
        uses: actions/upload-artifact@v2
        with:
         name: allure-results
         path: allure-results 

      - name: Publish Allure Report
        uses: actions/upload-pages-artifact@v1
        with:
          path: allure-report
      
      - name: Publish Allure Results
        uses: actions/upload-pages-artifact@v1
        with:
          path: allure-results

      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
